version: "3.7"
name: lms
services:
  mariadb:
    # image: mariadb:10.8
    image: ${MARIADB_IMAGE_NAME}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    # image: redis:alpine
    image: ${REDIS_IMAGE_NAME}

  frappe:
    # image: frappe/bench:latest
    image: ${FRAPPE_IMAGE_NAME}
    # command: bash /workspace/init.sh
    environment:
      # SHELL: /bin/bash       
      MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      ADMIN_PASSWORD=${ADMIN_PASSWORD}

    working_dir: /home/frappe
    volumes:
      # - .:/workspace
      - frappe-data:/workspace
      - frappe-dir:/home/frappe
    ports:
      - 8000:8000
      # - 9000:9000    
    depends_on:
          - mariadb
          - redis


volumes:
  mariadb-data:
  frappe-data:
  frappe-dir: